
name: Java CI with Maven for TextUtil

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # checkout action downloads the complete repository source code to the runner environment
    - uses: actions/checkout@v4
    
    - name: Set up JDK 24
    #  installs the JDK using the version specified
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        # Eclipse Temurin distribution provides enterprise-grade Java runtime environments
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Make hyperlink to jar-war file    # Tạo hyperlink để download build 
      uses: actions/upload-artifact@v4
      with:
          name: get_jar    # Hyperlink để download build, app
          path: staging
    - name: Publish test results
      uses: dorny/test-reporter@v1 # uses test reporter in of Github Action
      if: always()  # This ensures results are published even if tests fail
      with:
        name: Test Results
        path: target/surefire-reports/*.xml # use .xml file generated by Maven 
        reporter: java-junit  # intepreter by java-junit

